"""Lightweight ARC-AGI-3-style agent harness."""

__version__ = "0.4.0"

from arc_harness.core.actions import Action, ActionType, Frame, StepRecord
from arc_harness.core.agent import ArcAgent, DelegatingPlannerAgent, HandoffAgent, HeuristicAgent, RuleLearningAgent
from arc_harness.models.capabilities import (
    DEFAULT_CAPABILITY_REGISTRY,
    CapabilityError,
    CapabilityRegistration,
    CapabilityRegistry,
    ProviderDescriptor,
    make_default_capability_registry,
)
from arc_harness.runtime.checkpoint import CheckpointStore
from arc_harness.core.config import RunnerConfig
from arc_harness.memory.context import ContextBudget, ContextBundle, ContextInjector, ContextManager, ContextRole, ContextSection
from arc_harness.models.delegation import (
    DelegationConfig,
    DelegationError,
    DelegationManager,
    HandoffController,
    HandoffRecord,
    HandoffRule,
    SubAgent,
    SubAgentResult,
    SubTask,
)
from arc_harness.core.environment import ArcEnvironment, EnvironmentResult, validate_environment
from arc_harness.utils.errors import ErrorContext, HarnessError, ValidationError
from arc_harness.eval.evaluation import EvalCase, EvalCaseResult, EvalReport, EvaluationRunner, classify_failure, episode_metrics
from arc_harness.utils.events import AgentEvent
from arc_harness.runtime.guardrails import (
    ActionGuardrail,
    CoordinateBoundsGuardrail,
    FrameGuardrail,
    GuardrailDecision,
    GuardrailResult,
    MaxChangedCellsGuardrail,
    ResultGuardrail,
)
from arc_harness.runtime.hooks import ActionBudgetHook, Hook, HookManager, HookMatcher, JsonlTraceHook
from arc_harness.integrations.kaggle import KagglePackage, KaggleReadinessReport, ReadinessCheck, build_kaggle_package, build_submission_manifest, check_kaggle_readiness
from arc_harness.runtime.loop import EpisodeResult, EpisodeRunner
from arc_harness.runtime.loop_stages import (
    ActionExecutionStage,
    BuildContextStage,
    DecisionStage,
    DoneCheckStage,
    ExplorationStage,
    LoopRuntime,
    LoopStage,
    LoopState,
    PerceptionStage,
    PermissionStage,
    PlanDecisionStage,
    PlanningStage,
    StagePipeline,
    StopCheckStage,
    ToolUseStage,
    default_loop_stages,
    delegating_planner_loop_stages,
)
from arc_harness.memory.memory import DurableMemory, MemoryEntry, MemoryManager, WorkingMemory
from arc_harness.memory.memory_policy import MemoryPolicy
from arc_harness.memory.memory_store import LightweightEmbeddingIndex, SearchResult, StructuredMemoryStore
from arc_harness.models.models import (
    DEFAULT_MODEL_REGISTRY,
    CallableModel,
    CandidateAction,
    CandidateGenerator,
    CandidateRankingAgent,
    JsonPolicyModel,
    LocalModel,
    ModelBackedAgent,
    ModelInput,
    ModelOutput,
    ModelRegistry,
    QwenLocalRanker,
    build_agent_from_model_config,
    load_model_from_config,
)
from arc_harness.integrations.official import (
    ArcAgi3Config,
    EnvironmentFileCatalog,
    OfficialArcEnvironment,
    OfficialDependencyError,
    coerce_official_frame,
    create_official_environment,
    resolve_official_action,
)
from arc_harness.integrations.official_eval import OfficialSmokeReport, OfficialSmokeResult, OfficialSmokeRunner, discover_official_games
from arc_harness.core.policy import Decision, HookDecision
from arc_harness.eval.replay import ReplayEpisode, ReplayStep
from arc_harness.runtime.recovery import DefaultRecoveryPolicy, NoRecoveryPolicy, RecoveryDecision, RecoveryKind, RecoveryPolicy
from arc_harness.integrations.sandbox import LocalSubprocessSandbox, Sandbox, SandboxCommand, SandboxError, SandboxPolicy, SandboxPolicyError, SandboxResult
from arc_harness.models.subagents import DiffSubAgent, ExplorerSubAgent, PerceptionSubAgent, PlannerSubAgent
from arc_harness.runtime.thread import ArcThread
from arc_harness.runtime.tools import (
    RegisteredTool,
    ToolCall,
    ToolContext,
    ToolDispatcher,
    ToolError,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    default_tool_registry,
)
from arc_harness.eval.tracing import Span, Trace, TraceStore, TraceTimeline, TraceTimelineItem
from arc_harness.utils.validation import validate_action, validate_frame

__all__ = [
    "Action",
    "ActionBudgetHook",
    "ActionGuardrail",
    "ActionType",
    "ActionExecutionStage",
    "ArcAgi3Config",
    "ArcAgent",
    "ArcEnvironment",
    "ArcThread",
    "CapabilityError",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CheckpointStore",
    "CallableModel",
    "CandidateAction",
    "CandidateGenerator",
    "CandidateRankingAgent",
    "BuildContextStage",
    "CoordinateBoundsGuardrail",
    "ContextBudget",
    "ContextBundle",
    "ContextInjector",
    "ContextManager",
    "ContextRole",
    "ContextSection",
    "DEFAULT_MODEL_REGISTRY",
    "DEFAULT_CAPABILITY_REGISTRY",
    "DefaultRecoveryPolicy",
    "DecisionStage",
    "DoneCheckStage",
    "DurableMemory",
    "AgentEvent",
    "Decision",
    "DelegatingPlannerAgent",
    "DelegationConfig",
    "DelegationError",
    "DelegationManager",
    "DiffSubAgent",
    "EnvironmentResult",
    "EnvironmentFileCatalog",
    "ErrorContext",
    "EvalCase",
    "EvalCaseResult",
    "EvalReport",
    "EvaluationRunner",
    "TraceTimeline",
    "TraceTimelineItem",
    "ExplorerSubAgent",
    "ExplorationStage",
    "EpisodeResult",
    "EpisodeRunner",
    "Frame",
    "FrameGuardrail",
    "GuardrailDecision",
    "GuardrailResult",
    "HarnessError",
    "HandoffAgent",
    "HandoffController",
    "HandoffRecord",
    "HandoffRule",
    "HeuristicAgent",
    "HookDecision",
    "Hook",
    "HookMatcher",
    "HookManager",
    "JsonlTraceHook",
    "KagglePackage",
    "KaggleReadinessReport",
    "LocalSubprocessSandbox",
    "LoopRuntime",
    "LoopStage",
    "LoopState",
    "MemoryEntry",
    "MemoryManager",
    "MemoryPolicy",
    "ModelBackedAgent",
    "ModelInput",
    "ModelOutput",
    "ModelRegistry",
    "NoRecoveryPolicy",
    "LocalModel",
    "JsonPolicyModel",
    "QwenLocalRanker",
    "OfficialArcEnvironment",
    "OfficialDependencyError",
    "OfficialSmokeReport",
    "OfficialSmokeResult",
    "OfficialSmokeRunner",
    "PerceptionSubAgent",
    "PerceptionStage",
    "PermissionStage",
    "PlanDecisionStage",
    "PlanningStage",
    "PlannerSubAgent",
    "ProviderDescriptor",
    "ReplayEpisode",
    "ReplayStep",
    "RegisteredTool",
    "RecoveryDecision",
    "RecoveryKind",
    "RecoveryPolicy",
    "ReadinessCheck",
    "ResultGuardrail",
    "RuleLearningAgent",
    "RunnerConfig",
    "Sandbox",
    "SandboxCommand",
    "SandboxError",
    "SandboxPolicy",
    "SandboxPolicyError",
    "SandboxResult",
    "LightweightEmbeddingIndex",
    "SearchResult",
    "MaxChangedCellsGuardrail",
    "Span",
    "StagePipeline",
    "StepRecord",
    "StopCheckStage",
    "SubAgent",
    "SubAgentResult",
    "SubTask",
    "ToolCall",
    "ToolContext",
    "ToolDispatcher",
    "ToolError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolUseStage",
    "Trace",
    "TraceStore",
    "StructuredMemoryStore",
    "ValidationError",
    "WorkingMemory",
    "build_agent_from_model_config",
    "build_kaggle_package",
    "build_submission_manifest",
    "check_kaggle_readiness",
    "classify_failure",
    "coerce_official_frame",
    "create_official_environment",
    "discover_official_games",
    "episode_metrics",
    "default_loop_stages",
    "default_tool_registry",
    "delegating_planner_loop_stages",
    "load_model_from_config",
    "make_default_capability_registry",
    "resolve_official_action",
    "validate_action",
    "validate_environment",
    "validate_frame",
]
