"""Lightweight ARC-AGI-3-style agent harness."""

__version__ = "0.4.0"

from .actions import Action, ActionType, Frame, StepRecord
from .agent import ArcAgent, DelegatingPlannerAgent, HandoffAgent, HeuristicAgent, RuleLearningAgent
from .capabilities import (
    DEFAULT_CAPABILITY_REGISTRY,
    CapabilityError,
    CapabilityRegistration,
    CapabilityRegistry,
    ProviderDescriptor,
    make_default_capability_registry,
)
from .checkpoint import CheckpointStore
from .config import RunnerConfig
from .context import ContextBudget, ContextBundle, ContextInjector, ContextManager, ContextRole, ContextSection
from .delegation import (
    DelegationConfig,
    DelegationError,
    DelegationManager,
    HandoffController,
    HandoffRecord,
    HandoffRule,
    SubAgent,
    SubAgentResult,
    SubTask,
)
from .environment import ArcEnvironment, EnvironmentResult, validate_environment
from .errors import ErrorContext, HarnessError, ValidationError
from .evaluation import EvalCase, EvalCaseResult, EvalReport, EvaluationRunner, classify_failure, episode_metrics
from .events import AgentEvent
from .guardrails import (
    ActionGuardrail,
    CoordinateBoundsGuardrail,
    FrameGuardrail,
    GuardrailDecision,
    GuardrailResult,
    MaxChangedCellsGuardrail,
    ResultGuardrail,
)
from .hooks import ActionBudgetHook, Hook, HookManager, HookMatcher, JsonlTraceHook
from .kaggle import KagglePackage, KaggleReadinessReport, ReadinessCheck, build_kaggle_package, build_submission_manifest, check_kaggle_readiness
from .loop import EpisodeResult, EpisodeRunner
from .loop_stages import (
    ActionExecutionStage,
    BuildContextStage,
    DecisionStage,
    DoneCheckStage,
    ExplorationStage,
    LoopRuntime,
    LoopStage,
    LoopState,
    PerceptionStage,
    PermissionStage,
    PlanDecisionStage,
    PlanningStage,
    StagePipeline,
    StopCheckStage,
    ToolUseStage,
    default_loop_stages,
    delegating_planner_loop_stages,
)
from .memory import DurableMemory, MemoryEntry, MemoryManager, WorkingMemory
from .memory_policy import MemoryPolicy
from .memory_store import LightweightEmbeddingIndex, SearchResult, StructuredMemoryStore
from .models import (
    DEFAULT_MODEL_REGISTRY,
    CallableModel,
    JsonPolicyModel,
    LocalModel,
    ModelBackedAgent,
    ModelInput,
    ModelOutput,
    ModelRegistry,
    build_agent_from_model_config,
    load_model_from_config,
)
from .official import (
    ArcAgi3Config,
    EnvironmentFileCatalog,
    OfficialArcEnvironment,
    OfficialDependencyError,
    coerce_official_frame,
    create_official_environment,
    resolve_official_action,
)
from .official_eval import OfficialSmokeReport, OfficialSmokeResult, OfficialSmokeRunner, discover_official_games
from .policy import Decision, HookDecision
from .replay import ReplayEpisode, ReplayStep
from .recovery import DefaultRecoveryPolicy, NoRecoveryPolicy, RecoveryDecision, RecoveryKind, RecoveryPolicy
from .sandbox import LocalSubprocessSandbox, Sandbox, SandboxCommand, SandboxError, SandboxPolicy, SandboxPolicyError, SandboxResult
from .subagents import DiffSubAgent, ExplorerSubAgent, PerceptionSubAgent, PlannerSubAgent
from .thread import ArcThread
from .tools import (
    RegisteredTool,
    ToolCall,
    ToolContext,
    ToolDispatcher,
    ToolError,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    default_tool_registry,
)
from .tracing import Span, Trace, TraceStore, TraceTimeline, TraceTimelineItem
from .validation import validate_action, validate_frame

__all__ = [
    "Action",
    "ActionBudgetHook",
    "ActionGuardrail",
    "ActionType",
    "ActionExecutionStage",
    "ArcAgi3Config",
    "ArcAgent",
    "ArcEnvironment",
    "ArcThread",
    "CapabilityError",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CheckpointStore",
    "CallableModel",
    "BuildContextStage",
    "CoordinateBoundsGuardrail",
    "ContextBudget",
    "ContextBundle",
    "ContextInjector",
    "ContextManager",
    "ContextRole",
    "ContextSection",
    "DEFAULT_MODEL_REGISTRY",
    "DEFAULT_CAPABILITY_REGISTRY",
    "DefaultRecoveryPolicy",
    "DecisionStage",
    "DoneCheckStage",
    "DurableMemory",
    "AgentEvent",
    "Decision",
    "DelegatingPlannerAgent",
    "DelegationConfig",
    "DelegationError",
    "DelegationManager",
    "DiffSubAgent",
    "EnvironmentResult",
    "EnvironmentFileCatalog",
    "ErrorContext",
    "EvalCase",
    "EvalCaseResult",
    "EvalReport",
    "EvaluationRunner",
    "TraceTimeline",
    "TraceTimelineItem",
    "ExplorerSubAgent",
    "ExplorationStage",
    "EpisodeResult",
    "EpisodeRunner",
    "Frame",
    "FrameGuardrail",
    "GuardrailDecision",
    "GuardrailResult",
    "HarnessError",
    "HandoffAgent",
    "HandoffController",
    "HandoffRecord",
    "HandoffRule",
    "HeuristicAgent",
    "HookDecision",
    "Hook",
    "HookMatcher",
    "HookManager",
    "JsonlTraceHook",
    "KagglePackage",
    "KaggleReadinessReport",
    "LocalSubprocessSandbox",
    "LoopRuntime",
    "LoopStage",
    "LoopState",
    "MemoryEntry",
    "MemoryManager",
    "MemoryPolicy",
    "ModelBackedAgent",
    "ModelInput",
    "ModelOutput",
    "ModelRegistry",
    "NoRecoveryPolicy",
    "LocalModel",
    "JsonPolicyModel",
    "OfficialArcEnvironment",
    "OfficialDependencyError",
    "OfficialSmokeReport",
    "OfficialSmokeResult",
    "OfficialSmokeRunner",
    "PerceptionSubAgent",
    "PerceptionStage",
    "PermissionStage",
    "PlanDecisionStage",
    "PlanningStage",
    "PlannerSubAgent",
    "ProviderDescriptor",
    "ReplayEpisode",
    "ReplayStep",
    "RegisteredTool",
    "RecoveryDecision",
    "RecoveryKind",
    "RecoveryPolicy",
    "ReadinessCheck",
    "ResultGuardrail",
    "RuleLearningAgent",
    "RunnerConfig",
    "Sandbox",
    "SandboxCommand",
    "SandboxError",
    "SandboxPolicy",
    "SandboxPolicyError",
    "SandboxResult",
    "LightweightEmbeddingIndex",
    "SearchResult",
    "MaxChangedCellsGuardrail",
    "Span",
    "StagePipeline",
    "StepRecord",
    "StopCheckStage",
    "SubAgent",
    "SubAgentResult",
    "SubTask",
    "ToolCall",
    "ToolContext",
    "ToolDispatcher",
    "ToolError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolUseStage",
    "Trace",
    "TraceStore",
    "StructuredMemoryStore",
    "ValidationError",
    "WorkingMemory",
    "build_agent_from_model_config",
    "build_kaggle_package",
    "build_submission_manifest",
    "check_kaggle_readiness",
    "classify_failure",
    "coerce_official_frame",
    "create_official_environment",
    "discover_official_games",
    "episode_metrics",
    "default_loop_stages",
    "default_tool_registry",
    "delegating_planner_loop_stages",
    "load_model_from_config",
    "make_default_capability_registry",
    "resolve_official_action",
    "validate_action",
    "validate_environment",
    "validate_frame",
]
